version: '3.8'
services:
  web:
    build: ./project
    command: sh -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - web-db
      - web-cache
    volumes:
      - ./project:/code

  web-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env_db

  worker:
    build: ./project
    command: celery -A main.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - web-db
      - web-cache
    volumes:
      - ./project:/code


  web-cache:
    image: redis:7-alpine
    restart: always

