"""initial

Revision ID: d07d3e4f1773
Revises: 
Create Date: 2023-10-10 06:16:49.178275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd07d3e4f1773'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('operator_code', sa.String(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', mysql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_end', mysql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('tag_filter', sa.String(), nullable=True),
    sa.Column('operator_code_filter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('mailing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('mailings')
    op.drop_table('clients')
    # ### end Alembic commands ###
