"""initial

Revision ID: 772cd9ea6c9e
Revises: 
Create Date: 2023-10-07 11:04:23.737287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '772cd9ea6c9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('phone_number', sa.String(length=11), nullable=False),
                    sa.Column('operator_code', sa.String(), nullable=False),
                    sa.Column('tag', sa.Text(), nullable=False),
                    sa.Column('timezone', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('mailings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_start', sa.DateTime(), nullable=False),
                    sa.Column('date_end', sa.DateTime(), nullable=False),
                    sa.Column('date_stop', sa.DateTime(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('filter', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.Boolean(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('mailing_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
                    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('mailings')
    op.drop_table('clients')
    # ### end Alembic commands ###
